# Generated by Django 5.0.6 on 2026-09-11 11:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_url', models.URLField(max_length=500)),
                ('secret_key', models.CharField(help_text='Shared HMAC secret key for signing payload digests', max_length=128)),
                ('subscribed_events', models.JSONField(default=list, help_text="List of event topics: e.g. ['sales.order.created', 'inventory.stock.low']")),
                ('is_active', models.BooleanField(default=True)),
                ('retry_limit', models.PositiveIntegerField(default=5)),
                ('total_deliveries_count', models.PositiveBigIntegerField(default=0)),
                ('successful_deliveries_count', models.PositiveBigIntegerField(default=0)),
                ('failed_deliveries_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint Subscription',
                'verbose_name_plural': 'Webhook Endpoint Subscriptions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered (2xx Success)'), ('FAILED', 'Delivery Failed (4xx/5xx/Timeout)'), ('RETRYING', 'Queued for Backoff Retry')], default='DELIVERED', max_length=20)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('duration_ms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('signature_header', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='webhooks_engine.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='webhooks_engine.webhookevent')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Attempt',
                'verbose_name_plural': 'Webhook Delivery Attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
