# Generated by Django 5.0.6 on 2026-09-11 10:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('property_type', models.CharField(choices=[('COMMERCIAL_OFFICE', 'Commercial Office Tower'), ('RESIDENTIAL_APARTMENTS', 'Residential Multi-Family Complex'), ('RETAIL_MALL', 'Retail Shopping Center / Mall'), ('INDUSTRIAL_PARK', 'Industrial Logistics Park'), ('MIXED_USE', 'Mixed-Use Commercial & Residential')], default='COMMERCIAL_OFFICE', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('total_units_count', models.PositiveIntegerField(default=0)),
                ('manager_name', models.CharField(blank=True, max_length=150)),
                ('manager_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Property Complexes',
            },
        ),
        migrations.CreateModel(
            name='PropertyTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_or_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('tax_id_or_ssn', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=150)),
                ('is_corporate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('floor_number', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('OFFICE_SUITE', 'Executive Office Suite'), ('APARTMENT_1BHK', '1-Bedroom Apartment'), ('APARTMENT_2BHK', '2-Bedroom Apartment'), ('APARTMENT_PENTHOUSE', 'Luxury Penthouse'), ('RETAIL_SHOP', 'Ground Floor Retail Storefront'), ('WAREHOUSE_BAY', 'Warehouse Storage Bay')], default='OFFICE_SUITE', max_length=30)),
                ('square_feet', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=8)),
                ('base_monthly_rent', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=12)),
                ('cam_fee_monthly', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('occupancy_status', models.CharField(choices=[('VACANT', 'Vacant / Ready to Lease'), ('LEASED', 'Occupied / Leased'), ('UNDER_MAINTENANCE', 'Under Renovation / Maintenance'), ('RESERVED', 'Reserved / LOI Signed')], default='VACANT', max_length=20)),
                ('amenities', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='real_estate_pms.propertycomplex')),
            ],
            options={
                'unique_together': {('complex', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('issue_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing & Drainage'), ('ELECTRICAL', 'Electrical & Lighting'), ('HVAC', 'HVAC Air Conditioning & Heating'), ('STRUCTURAL', 'Carpentry & Structural'), ('JANITORIAL', 'Janitorial & Cleaning'), ('ELEVATOR', 'Elevator / Lift Service'), ('FIRE_SAFETY', 'Fire Alarm & Safety')], default='PLUMBING', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Urgent'), ('EMERGENCY', 'Critical Emergency')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Work Order Logged'), ('ASSIGNED', 'Assigned to Vendor / Tech'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed & Inspected'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('assigned_technician', models.CharField(blank=True, max_length=150)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='real_estate_pms.propertytenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='real_estate_pms.propertyunit')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cam_fee_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_deposit_held', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_escalation_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('payment_due_day', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Proposal'), ('ACTIVE', 'Active In-Force'), ('EXPIRED', 'Naturally Expired'), ('TERMINATED', 'Early Terminated')], default='ACTIVE', max_length=20)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('signed_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='real_estate_pms.propertytenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='real_estate_pms.propertyunit')),
            ],
        ),
        migrations.CreateModel(
            name='TenantRentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cam_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('utility_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_invoices', to='real_estate_pms.leaseagreement')),
            ],
        ),
    ]
