# Generated by Django 5.0.6 on 2026-09-11 11:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('requests_per_minute', models.PositiveIntegerField(default=60)),
                ('requests_per_hour', models.PositiveIntegerField(default=1000)),
                ('burst_limit', models.PositiveIntegerField(default=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Policy',
                'verbose_name_plural': 'Rate Limit Policies',
            },
        ),
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('ip_whitelist', models.TextField(blank=True, help_text='Comma-separated IPv4/IPv6 addresses or CIDRs. Leave blank for unrestricted.')),
                ('allowed_scopes', models.CharField(default='read:inventory,read:sales,write:orders', help_text='Comma-separated scopes', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='organizations.organization')),
                ('rate_limit_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_gateway.ratelimitpolicy')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('LIVE', 'Production / Live (nx_live_)'), ('TEST', 'Sandbox / Testing (nx_test_)')], default='LIVE', max_length=10)),
                ('name', models.CharField(default='Default Integration Key', max_length=150)),
                ('key_prefix', models.CharField(max_length=20)),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('raw_key_preview', models.CharField(max_length=40)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_calls_count', models.PositiveBigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api_gateway.apiclient')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIGatewayRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('http_method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField(db_index=True)),
                ('response_time_ms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api_gateway.apikey')),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
