# Generated by Django 5.0.6 on 2026-09-11 10:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('vendor_tax_id', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('facility_address', models.TextField()),
                ('toll_processing_types', models.TextField(help_text='e.g. CNC Milling, Heat Treatment, Surface Anodizing, PCB Assembly')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subcontractor / Job Worker',
                'verbose_name_plural': 'Subcontractors / Job Workers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_processing_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_service_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Work Order'), ('MATERIALS_DISPATCHED', 'Raw Materials Issued to Vendor'), ('IN_PROCESSING', 'Toll Processing In-Progress at Vendor'), ('PARTIALLY_RECEIVED', 'Partially Received Finished Goods'), ('COMPLETED', 'Completed & Reconciled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_orders', to='inventory.product')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='subcontracting.subcontractorvendor')),
            ],
            options={
                'verbose_name': 'Subcontract Work Order',
                'verbose_name_plural': 'Subcontract Work Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractMaterialDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_challan_number', models.CharField(max_length=50, unique=True)),
                ('quantity_issued', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_number', models.CharField(default='LOT-001', max_length=50)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_dispatches', to='inventory.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='subcontracting.subcontractorder')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('scrap_material_reported', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_yield_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor_delivery_note_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='subcontracting.subcontractorder')),
            ],
            options={
                'verbose_name': 'Subcontract Goods Receipt Note (SGRN)',
                'verbose_name_plural': 'Subcontract Goods Receipt Notes (SGRN)',
                'ordering': ['-created_at'],
            },
        ),
    ]
