# Generated by Django 5.0.6 on 2026-09-11 11:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('connector_type', models.CharField(choices=[('STRIPE', 'Stripe Billing & Global Payments Gateway'), ('SALESFORCE', 'Salesforce CRM Enterprise Synchronizer'), ('FEDEX', 'FedEx Logistics & Freight Carrier Bridge'), ('SAP_BRIDGE', 'SAP ERP & NetSuite General Ledger Bridge'), ('SHOPIFY', 'Shopify E-Commerce Storefront Connector')], max_length=30)),
                ('auth_type', models.CharField(choices=[('API_KEY', 'Bearer / API Secret Token'), ('OAUTH2', 'OAuth 2.0 PKCE / Authorization Code'), ('BASIC_AUTH', 'HTTP Basic Credentials'), ('WEBHOOK_SECRET', 'Cryptographic Webhook Secret')], default='API_KEY', max_length=30)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('credentials_config', models.JSONField(blank=True, default=dict, help_text='Encrypted/masked configuration dictionary')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle / Ready'), ('RUNNING', 'Synchronization In-Progress'), ('SUCCESS', 'Healthy / Last Sync Succeeded'), ('ERROR', 'Error / Sync Failed')], default='IDLE', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enterprise Integration Connector',
                'verbose_name_plural': 'Enterprise Integration Connectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(default='MANUAL_TRIGGER', max_length=50)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('PARTIAL', 'Completed with Warnings')], default='SUCCESS', max_length=20)),
                ('log_details', models.TextField(blank=True)),
                ('duration_seconds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations_sdk.integrationconnector')),
            ],
            options={
                'verbose_name': 'Integration Sync Log',
                'verbose_name_plural': 'Integration Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntitySyncMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('CUSTOMER', 'Customer / Account Record'), ('PRODUCT', 'Inventory Product SKU'), ('SALES_ORDER', 'Sales Order Record'), ('INVOICE', 'Billing Invoice'), ('PAYMENT', 'Payment Settlement'), ('JOURNAL_ENTRY', 'GL Journal Entry')], max_length=30)),
                ('local_id', models.PositiveIntegerField()),
                ('external_reference_id', models.CharField(db_index=True, max_length=150)),
                ('sync_direction', models.CharField(choices=[('INBOUND', 'Inbound (External -> Nexora)'), ('OUTBOUND', 'Outbound (Nexora -> External)'), ('BIDIRECTIONAL', 'Bi-directional Two-Way Sync')], default='BIDIRECTIONAL', max_length=20)),
                ('last_sync_timestamp', models.DateTimeField(auto_now=True)),
                ('sync_payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations_sdk.integrationconnector')),
            ],
            options={
                'verbose_name': 'Entity Sync Mapping',
                'verbose_name_plural': 'Entity Sync Mappings',
                'ordering': ['-last_sync_timestamp'],
                'unique_together': {('connector', 'entity_type', 'local_id')},
            },
        ),
    ]
