# Generated by Django 5.0.6 on 2026-09-11 11:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reporting_currency', models.CharField(default='USD', max_length=10)),
                ('fiscal_year_end_month', models.PositiveSmallIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_consolidation_groups', to='organizations.organization')),
                ('subsidiary_organizations', models.ManyToManyField(related_name='subsidiary_consolidation_groups', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Consolidation Group',
                'verbose_name_plural': 'Consolidation Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(max_length=50, unique=True)),
                ('statement_type', models.CharField(choices=[('BALANCE_SHEET', 'Consolidated Statement of Financial Position (Balance Sheet)'), ('PROFIT_AND_LOSS', 'Consolidated Statement of Profit & Loss (Income Statement)'), ('CASH_FLOW', 'Consolidated Statement of Cash Flows')], default='BALANCE_SHEET', max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reporting_currency', models.CharField(default='USD', max_length=10)),
                ('gross_total_parent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gross_total_subsidiaries', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_eliminations', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_consolidated_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency_translation_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Consolidation Matrix'), ('ELIMINATED', 'Intercompany Eliminations Applied'), ('FINALIZED', 'Audited & Board Approved')], default='ELIMINATED', max_length=20)),
                ('statement_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='consolidation.consolidationgroup')),
            ],
            options={
                'verbose_name': 'Consolidated Financial Statement',
                'verbose_name_plural': 'Consolidated Financial Statements',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(default='USD', max_length=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('spot_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('average_monthly_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('closing_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IAS 21 Currency Exchange Rate',
                'verbose_name_plural': 'IAS 21 Currency Exchange Rates',
                'ordering': ['-effective_date'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='InterCompanyEliminationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('AR_AP_BALANCE', 'Intercompany Accounts Receivable / Payable Elimination'), ('REVENUE_EXPENSE', 'Intercompany Revenue & Outside Processing Expense'), ('DIVIDEND_ELIM', 'Intercompany Dividend & Equity Elimination'), ('LOAN_INTEREST', 'Intercompany Loan & Financing Interest')], default='AR_AP_BALANCE', max_length=30)),
                ('source_account_code', models.CharField(help_text='e.g. 1100 (Trade AR)', max_length=50)),
                ('offset_account_code', models.CharField(help_text='e.g. 2010 (Trade AP)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_rules', to='consolidation.consolidationgroup')),
            ],
            options={
                'verbose_name': 'Intercompany Elimination Rule',
                'verbose_name_plural': 'Intercompany Elimination Rules',
            },
        ),
    ]
