# Generated by Django 5.0.6 on 2026-09-11 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed & Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('transfer_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('total_capacity_sqft', models.PositiveIntegerField(default=10000)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='organizations.branch')),
            ],
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='warehouse.warehouse'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(max_length=20)),
                ('shelf', models.CharField(max_length=20)),
                ('bin_number', models.CharField(max_length=20)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehouse.zone')),
            ],
            options={
                'unique_together': {('zone', 'aisle', 'shelf', 'bin_number')},
            },
        ),
    ]
