# Generated by Django 5.0.6 on 2026-09-15 10:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBidRfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_delivery_date', models.DateField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open for Bidding'), ('CLOSED', 'Bidding Closed'), ('EVALUATING', 'Evaluating Bids'), ('AWARDED', 'Awarded to Supplier'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rfqs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBidRfqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.PositiveIntegerField()),
                ('target_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='inventory.product')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor_portal.supplierbidrfq')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoiceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pdf_document_url', models.CharField(blank=True, max_length=255)),
                ('match_status', models.CharField(choices=[('PENDING_MATCH', 'Pending 3-Way Match'), ('MATCH_PASSED', '3-Way Match Passed (100% Verified)'), ('MATCH_FAILED', 'Match Discrepancy Flagged'), ('APPROVED', 'Approved for Payment Batch'), ('PAID', 'Settled & Paid')], default='PENDING_MATCH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_invoices', to='organizations.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='purchasing.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatchVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('grn_received_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('quantity_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('match_status', models.CharField(choices=[('FULL_MATCH', 'Full 3-Way Match (Zero Discrepancy)'), ('PRICE_VARIANCE', 'Price Variance Flagged'), ('QUANTITY_VARIANCE', 'Quantity Variance Flagged'), ('DISCREPANCY_FLAGGED', 'Critical Discrepancy Flagged'), ('OVERRIDDEN_BY_MANAGER', 'Manually Approved & Overridden')], default='FULL_MATCH', max_length=30)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('auditor_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_verifications', to='organizations.organization')),
                ('vendor_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_way_match', to='vendor_portal.vendorinvoiceupload')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPortalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('rating_score', models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=3)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Fully Compliant (ISO / SOC2)'), ('CONDITIONAL', 'Conditional Approval'), ('AUDIT_REQUIRED', 'Audit Required'), ('SUSPENDED', 'Temporarily Suspended')], default='COMPLIANT', max_length=20)),
                ('bank_swift_code', models.CharField(blank=True, max_length=50)),
                ('bank_iban', models.CharField(blank=True, max_length=50)),
                ('tax_id_number', models.CharField(blank=True, max_length=100)),
                ('portal_access_enabled', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profiles', to='organizations.organization')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to='purchasing.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendorinvoiceupload',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vendor_portal.vendorportalprofile'),
        ),
        migrations.CreateModel(
            name='SupplierBidSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('AWARDED', 'Awarded'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('composite_evaluation_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('vendor_remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_submissions', to='organizations.organization')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='vendor_portal.supplierbidrfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='vendor_portal.vendorportalprofile')),
            ],
            options={
                'ordering': ['-composite_evaluation_score', 'total_bid_amount'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceShippingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn_number', models.CharField(max_length=50, unique=True)),
                ('carrier_name', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_arrival_date', models.DateField()),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched from Supplier Dock'), ('IN_TRANSIT', 'In Transit / Freight Line'), ('DELIVERED', 'Delivered at Nexora Facility'), ('VERIFIED', 'Verified & Received into Inventory'), ('EXCEPTION', 'Logistics Exception / Delayed')], default='DISPATCHED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='organizations.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='purchasing.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='vendor_portal.vendorportalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
