# Generated by Django 5.0.6 on 2026-09-11 10:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='e.g. FEDEX, DHL, MAERSK, MSC, CMA-CGM', max_length=50, unique=True)),
                ('carrier_type', models.CharField(choices=[('ROAD', 'Road Freight Carrier (FTL / LTL)'), ('AIR', 'Airlines & Air Cargo (IATA)'), ('OCEAN', 'Ocean Container Shipping Line'), ('RAIL', 'Railways Intermodal'), ('MULTIMODAL', 'Multimodal 3PL Integrator')], default='ROAD', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('tracking_url_template', models.CharField(blank=True, help_text='Template URL with {tracking_number} placeholder', max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Carrier',
                'verbose_name_plural': 'Shipping Carriers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreightConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=uuid.uuid4, help_text='Master Air Waybill (MAWB) or Bill of Lading #', max_length=64, unique=True)),
                ('transport_mode', models.CharField(choices=[('AIR_FREIGHT', 'Air Waybill (AWB)'), ('OCEAN_FCL', 'Ocean Bill of Lading (BOL - FCL)'), ('OCEAN_LCL', 'Ocean Bill of Lading (BOL - LCL)'), ('ROAD_FTL', 'Road Consignment (FTL)'), ('ROAD_LTL', 'Road Consignment (LTL)')], default='AIR_FREIGHT', max_length=20)),
                ('incoterms', models.CharField(choices=[('EXW', 'EXW - Ex Works'), ('FOB', 'FOB - Free on Board'), ('CIF', 'CIF - Cost, Insurance and Freight'), ('DDP', 'DDP - Delivered Duty Paid'), ('DAP', 'DAP - Delivered at Place'), ('CFR', 'CFR - Cost and Freight')], default='FOB', max_length=10)),
                ('shipper_name', models.CharField(max_length=200)),
                ('shipper_address', models.TextField()),
                ('shipper_city', models.CharField(max_length=100)),
                ('shipper_country', models.CharField(default='United States', max_length=100)),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_address', models.TextField()),
                ('consignee_city', models.CharField(max_length=100)),
                ('consignee_country', models.CharField(default='Germany', max_length=100)),
                ('origin_hub', models.CharField(default='JFK International Airport', max_length=100)),
                ('destination_hub', models.CharField(default='Frankfurt Airport (FRA)', max_length=100)),
                ('total_packages_count', models.PositiveIntegerField(default=1)),
                ('actual_gross_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('volumetric_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('chargeable_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('total_volume_cbm', models.DecimalField(decimal_places=3, default=Decimal('0.060'), max_digits=10)),
                ('declared_customs_value', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=12)),
                ('status', models.CharField(choices=[('BOOKED', 'Booking Confirmed / Manifest Created'), ('PICKED_UP', 'Cargo Picked Up from Shipper'), ('AT_TERMINAL', 'Received at Gateway Terminal'), ('IN_CUSTOMS', 'Customs Clearance In-Progress'), ('IN_TRANSIT', 'In-Transit / Linehaul Flight / Voyage'), ('OUT_FOR_DELIVERY', 'Out for Final Mile Delivery'), ('DELIVERED', 'Delivered & POD Signed'), ('EXCEPTION', 'Exception / Delay / Customs Hold')], default='BOOKED', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_departure', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('proof_of_delivery_signature', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_consignments', to='sales.customer')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='logistics_3pl.shippingcarrier')),
            ],
            options={
                'verbose_name': 'Freight Consignment (AWB/BOL)',
                'verbose_name_plural': 'Freight Consignments (AWB/BOL)',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='FreightConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('BOX', 'Standard Carton / Box'), ('PALLET', 'Euro / Standard Wooden Pallet'), ('CRATE', 'Heavy Wooden Crate'), ('DRUM', 'Steel / Plastic Drum'), ('CONTAINER_20FT', '20ft Standard Dry Container'), ('CONTAINER_40FT', '40ft High Cube Container')], default='BOX', max_length=20)),
                ('package_description', models.CharField(default='Commercial Electronics & Parts', max_length=255)),
                ('length_cm', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('width_cm', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=8)),
                ('height_cm', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('hs_code', models.CharField(default='8471.30', max_length=20)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('un_number', models.CharField(blank=True, help_text='e.g. UN3481 for Lithium Ion Batteries', max_length=10)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics_3pl.freightconsignment')),
            ],
            options={
                'verbose_name': 'Consignment Package Item',
                'verbose_name_plural': 'Consignment Package Items',
            },
        ),
        migrations.CreateModel(
            name='FreightShippingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('base_freight_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_surcharge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customs_brokerage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('origin_handling_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('destination_handling_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Settled & Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freight_invoice', to='logistics_3pl.freightconsignment')),
            ],
            options={
                'verbose_name': 'Freight Shipping Invoice',
                'verbose_name_plural': 'Freight Shipping Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightRateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(default='United States', max_length=100)),
                ('origin_zone', models.CharField(help_text='e.g. US-EAST, JFK, SHANGHAI', max_length=100)),
                ('destination_country', models.CharField(default='Germany', max_length=100)),
                ('destination_zone', models.CharField(help_text='e.g. EU-CENTRAL, FRA, ROTTERDAM', max_length=100)),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air Cargo Express (IATA Factor 5000)'), ('OCEAN_FCL', 'Ocean Full Container Load (FCL)'), ('OCEAN_LCL', 'Ocean Less than Container Load (LCL)'), ('ROAD_FTL', 'Road Full Truckload (FTL)'), ('ROAD_LTL', 'Road Less than Truckload (LTL)')], default='AIR', max_length=20)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=10)),
                ('fuel_surcharge_percentage', models.DecimalField(decimal_places=2, default=Decimal('12.50'), max_digits=5)),
                ('security_surcharge_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=6)),
                ('transit_days_min', models.PositiveIntegerField(default=2)),
                ('transit_days_max', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='logistics_3pl.shippingcarrier')),
            ],
            options={
                'verbose_name': 'Freight Rate Matrix',
                'verbose_name_plural': 'Freight Rate Matrices',
                'ordering': ['carrier', 'origin_zone', 'destination_zone'],
            },
        ),
        migrations.CreateModel(
            name='TransitMilestoneCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=150)),
                ('status_title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='logistics_3pl.freightconsignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transit Milestone Checkpoint',
                'verbose_name_plural': 'Transit Milestone Checkpoints',
                'ordering': ['-timestamp'],
            },
        ),
    ]
