# Generated by Django 5.0.6 on 2026-09-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Gasoline/Petrol'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=30)),
                ('current_odometer_km', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & On Route'), ('AVAILABLE', 'Available at Depot'), ('MAINTENANCE', 'Under Service / Repair'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='fleet.driver')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_location', models.CharField(max_length=150)),
                ('end_location', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purpose', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_km', models.PositiveIntegerField()),
                ('station', models.CharField(default='Shell Fleet Station', max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.vehicle')),
            ],
        ),
    ]
