# Generated by Django 5.0.6 on 2026-09-11 10:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_identifier', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('statement_format', models.CharField(choices=[('CSV', 'Standard Bank CSV'), ('OFX', 'OFX (Open Financial Exchange)'), ('MT940', 'SWIFT MT940 Electronic Statement'), ('CAMT053', 'ISO 20022 CAMT.053 XML'), ('QIF', 'Quicken Interchange Format (QIF)')], default='CSV', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_lines_count', models.PositiveIntegerField(default=0)),
                ('reconciled_lines_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported (Pending Reconciliation)'), ('IN_PROGRESS', 'Reconciliation In-Progress'), ('RECONCILED', 'Fully Reconciled & Balanced')], default='IMPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='accounting.bankaccount')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('raw_description', models.TextField()),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit (Cash Withdrawal / Outflow)'), ('CREDIT', 'Credit (Deposit / Inflow)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=150)),
                ('counterparty_name', models.CharField(blank=True, max_length=200)),
                ('counterparty_account', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched / Pending'), ('AUTO_MATCHED', 'Auto-Matched by Rule Engine'), ('MANUALLY_MATCHED', 'Manually Reconciled'), ('IGNORED', 'Ignored / Skipped')], default='UNMATCHED', max_length=20)),
                ('match_confidence_score', models.PositiveIntegerField(default=0, help_text='0 to 100 confidence score')),
                ('match_rule_applied', models.CharField(blank=True, max_length=150)),
                ('matched_journal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_statement_lines', to='accounting.journalitem')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_statement_lines', to='sales.payment')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reconciliation.bankstatement')),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'verbose_name_plural': 'Bank Statement Lines',
                'ordering': ['statement', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('rule_type', models.CharField(choices=[('EXACT_AMOUNT_AND_DATE', 'Exact Amount & Exact Date Match'), ('AMOUNT_AND_REF', 'Exact Amount & Reference Match'), ('DESCRIPTION_REGEX', 'Description RegEx Keyword Pattern'), ('COUNTERPARTY_MATCH', 'Counterparty Name & Amount Match'), ('TOLERANT_DATE', 'Exact Amount with +/- N Days Date Tolerance')], default='EXACT_AMOUNT_AND_DATE', max_length=30)),
                ('regex_pattern', models.CharField(blank=True, help_text='RegEx for description or reference', max_length=255)),
                ('date_tolerance_days', models.PositiveIntegerField(default=3)),
                ('min_confidence_score', models.PositiveIntegerField(default=80)),
                ('auto_post_adjusting_entry', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('contra_account', models.ForeignKey(blank=True, help_text='Target account for automated adjustments (e.g. Bank Fees, Interest Income)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
            ],
            options={
                'verbose_name': 'Reconciliation Rule',
                'verbose_name_plural': 'Reconciliation Rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('statement_closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('system_gl_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unreconciled_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In-Progress Audit'), ('BALANCED', 'Balanced & Finalized')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='accounting.bankaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reconciliation.bankstatement')),
            ],
            options={
                'verbose_name': 'Reconciliation Session',
                'verbose_name_plural': 'Reconciliation Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
