# Generated by Django 5.0.6 on 2026-09-11 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INWARD_GRN', 'Inward Raw Material / Vendor GRN Gate'), ('IN_PROCESS', 'In-Process Shop Floor Routing Checkpoint'), ('FINAL_DISPATCH', 'Final Pre-Dispatch QA Gate')], default='INWARD_GRN', max_length=30)),
                ('sampling_standard', models.CharField(choices=[('AQL_1_0', 'AQL 1.0 (High Precision / Tightened)'), ('AQL_2_5', 'AQL 2.5 (Standard Industrial Normal)'), ('AQL_4_0', 'AQL 4.0 (General Commercial Reduced)'), ('FULL_100', '100% Full Lot Inspection')], default='AQL_2_5', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality Inspection Plan',
                'verbose_name_plural': 'Quality Inspection Plans',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=150)),
                ('measurement_unit', models.CharField(default='mm', max_length=30)),
                ('min_acceptable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_acceptable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='quality_control.inspectionplan')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncr_number', models.CharField(max_length=50, unique=True)),
                ('defect_title', models.CharField(max_length=200)),
                ('defect_severity', models.CharField(choices=[('CRITICAL', 'Critical Defect (Safety / Zero Tolerance)'), ('MAJOR', 'Major Defect (Functional Failure)'), ('MINOR', 'Minor Defect (Cosmetic / Packaging)')], default='MAJOR', max_length=20)),
                ('defect_description', models.TextField()),
                ('root_cause_analysis', models.TextField(blank=True)),
                ('containment_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open Defect Logged'), ('UNDER_INVESTIGATION', 'Under 5-Why / Ishikawa Investigation'), ('CAPA_INITIATED', 'CAPA Action Plan Formulated'), ('CLOSED', 'Verified & Closed')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non-Conformance Report (NCR)',
                'verbose_name_plural': 'Non-Conformance Reports (NCR)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Action (Immediate Fix)'), ('PREVENTIVE', 'Preventive Action (Systemic Recurrence Prevention)')], default='CORRECTIVE', max_length=20)),
                ('action_description', models.TextField()),
                ('assigned_owner', models.CharField(max_length=150)),
                ('target_due_date', models.DateField()),
                ('verification_evidence', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='quality_control.nonconformancereport')),
            ],
        ),
        migrations.CreateModel(
            name='QualityInspectionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('reference_type', models.CharField(default='GRN', max_length=50)),
                ('reference_code', models.CharField(max_length=100)),
                ('lot_size', models.PositiveIntegerField(default=100)),
                ('sample_size', models.PositiveIntegerField(default=13)),
                ('inspected_quantity', models.PositiveIntegerField(default=13)),
                ('accepted_quantity', models.PositiveIntegerField(default=13)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('disposition', models.CharField(choices=[('ACCEPTED', 'Accepted / Released to Stock'), ('REJECTED', 'Rejected / Quarantined'), ('ACCEPTED_DEVIATION', 'Accepted Under Engineering Deviation'), ('REWORK', 'Returned to Shop Floor for Rework')], default='ACCEPTED', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inspection Sampling'), ('IN_TESTING', 'Testing / Measurement In Progress'), ('COMPLETED', 'Inspection Complete & Certified')], default='PENDING', max_length=20)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('inspector_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='quality_control.inspectionplan')),
            ],
            options={
                'verbose_name': 'Quality Inspection Ticket',
                'verbose_name_plural': 'Quality Inspection Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='nonconformancereport',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to='quality_control.qualityinspectionticket'),
        ),
        migrations.CreateModel(
            name='InspectionResultMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_conforming', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_control.inspectioncharacteristic')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='quality_control.qualityinspectionticket')),
            ],
        ),
    ]
