# Generated by Django 5.0.6 on 2026-09-11 10:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('forecast_demand_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('confirmed_so_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('planned_production_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Proposal'), ('APPROVED', 'Approved by Operations'), ('IN_EXECUTION', 'In-Execution on Floor'), ('COMPLETED', 'Schedule Fulfilled')], default='APPROVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mps_entries', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Master Production Schedule (MPS)',
                'verbose_name_plural': 'Master Production Schedules (MPS)',
                'ordering': ['period_start', 'product'],
            },
        ),
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(max_length=50, unique=True)),
                ('planning_horizon_days', models.PositiveIntegerField(default=90)),
                ('include_forecast', models.BooleanField(default=True)),
                ('include_safety_stock', models.BooleanField(default=True)),
                ('total_planned_orders_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Computation Running'), ('COMPLETED', 'Calculated & Ready'), ('APPLIED', 'Orders Released to Supply Chain'), ('CANCELLED', 'Cancelled / Discarded')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MRP Run Execution',
                'verbose_name_plural': 'MRP Run Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRPRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_date', models.DateField()),
                ('gross_requirement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_on_hand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scheduled_receipts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_requirement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_action', models.CharField(choices=[('PURCHASE_ORDER', 'Generate Purchase Order (External Buy)'), ('PRODUCTION_ORDER', 'Generate Production / Work Order (Internal Make)'), ('TRANSFER', 'Generate Inter-Warehouse Transfer')], default='PURCHASE_ORDER', max_length=30)),
                ('planned_order_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('order_release_date', models.DateField()),
                ('status', models.CharField(choices=[('RECOMMENDED', 'MRP Planned Recommendation'), ('RELEASED', 'Released to Purchasing / Manufacturing'), ('DISMISSED', 'Dismissed by Planner')], default='RECOMMENDED', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_requirements', to='inventory.product')),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mrp_planning.mrprun')),
            ],
            options={
                'verbose_name': 'MRP Planned Order Requirement',
                'verbose_name_plural': 'MRP Planned Order Requirements',
                'ordering': ['requirement_date', 'product'],
            },
        ),
        migrations.CreateModel(
            name='SafetyStockRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_safety_stock', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('economic_order_quantity', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_rules', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_rules', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Safety Stock & Reorder Rule',
                'verbose_name_plural': 'Safety Stock & Reorder Rules',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
