# Generated by Django 5.0.6 on 2026-09-11 11:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FXHedgingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('FORWARD', 'FX Outright Forward Contract'), ('OPTION', 'Currency Collar / Vanilla Option'), ('CURRENCY_SWAP', 'Cross-Currency Interest Rate Swap')], default='FORWARD', max_length=30)),
                ('counterparty_bank', models.CharField(max_length=150)),
                ('notional_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_currency', models.CharField(default='EUR', max_length=10)),
                ('quote_currency', models.CharField(default='USD', max_length=10)),
                ('strike_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('maturity_date', models.DateField()),
                ('mark_to_market_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In-Effect'), ('SETTLED', 'Matured & Settled'), ('EXPIRED', 'Expired / Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FX Hedging Contract',
                'verbose_name_plural': 'FX Hedging Contracts',
                'ordering': ['-maturity_date'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_name', models.CharField(max_length=200)),
                ('forecast_period_days', models.PositiveIntegerField(default=90)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('opening_cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('projected_inflows_ar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('projected_outflows_ap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('projected_payroll_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('projected_closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_cash_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Treasury Liquidity Forecast',
                'verbose_name_plural': 'Treasury Liquidity Forecasts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CashPoolHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pool_code', models.CharField(max_length=50, unique=True)),
                ('pool_method', models.CharField(choices=[('ZERO_BALANCE_SWEEP', 'Zero-Balance Account (ZBA) Sweeping'), ('TARGET_BALANCE_SWEEP', 'Target Balance Concentration Sweeping'), ('NOTIONAL_POOLING', 'Multi-Currency Notional Pooling')], default='TARGET_BALANCE_SWEEP', max_length=30)),
                ('target_balance_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool_leader_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_cash_pools', to='accounting.bankaccount')),
            ],
            options={
                'verbose_name': 'Cash Concentration Pool',
                'verbose_name_plural': 'Cash Concentration Pools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashSweepingExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_number', models.CharField(max_length=50, unique=True)),
                ('total_swept_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_swept_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfers_count', models.PositiveIntegerField(default=0)),
                ('transfers_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweeping_executions', to='treasury_cash.cashpoolheader')),
            ],
            options={
                'verbose_name': 'Cash Sweeping Execution Run',
                'verbose_name_plural': 'Cash Sweeping Execution Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashPoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('min_transfer_threshold', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_pool_participations', to='accounting.bankaccount')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='treasury_cash.cashpoolheader')),
            ],
            options={
                'verbose_name': 'Cash Pool Participant Account',
                'verbose_name_plural': 'Cash Pool Participant Accounts',
                'ordering': ['priority'],
                'unique_together': {('pool', 'bank_account')},
            },
        ),
    ]
