# Generated by Django 5.0.6 on 2026-09-15 10:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=14)),
                ('credit_balance_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_terms', models.CharField(choices=[('NET15', 'Net 15 Days'), ('NET30', 'Net 30 Days'), ('NET60', 'Net 60 Days'), ('NET90', 'Net 90 Days'), ('DUE_ON_RECEIPT', 'Due Upon Receipt')], default='NET30', max_length=20)),
                ('discount_tier_name', models.CharField(default='Standard Wholesale Tier', max_length=100)),
                ('tax_exemption_number', models.CharField(blank=True, max_length=100)),
                ('portal_access_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_profile', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_accounts', to='organizations.organization')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_accounts', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BCatalogPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('tier_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('b2b_account', models.ForeignKey(blank=True, help_text='Null applies globally to all B2B accounts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_price_tiers', to='b2b_portal.b2baccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_price_tiers', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_price_tiers', to='inventory.product')),
            ],
            options={
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='DigitalPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=64, unique=True)),
                ('payment_gateway', models.CharField(choices=[('STRIPE', 'Stripe Enterprise Connect'), ('PAYPAL', 'PayPal B2B Checkout'), ('ACH_TRANSFER', 'Direct Bank ACH Transfer'), ('WIRE_TRANSFER', 'Corporate Wire Transfer'), ('CORPORATE_CARD', 'Commercial Credit Card')], default='STRIPE', max_length=30)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured / Paid'), ('FAILED', 'Failed / Declined'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('receipt_url', models.URLField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('b2b_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_payments', to='b2b_portal.b2baccount')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_digital_payments', to='sales.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_payments', to='organizations.organization')),
                ('posted_gl_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_gateway_tx', to='sales.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Customer Decision'), ('APPROVED', 'Approved by Buyer'), ('REJECTED', 'Rejected by Buyer'), ('EXPIRED', 'Offer Expired'), ('CONVERTED', 'Converted to Sales Order')], default='PENDING', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('b2b_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_approvals', to='b2b_portal.b2baccount')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_b2b_quotes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_approvals', to='organizations.organization')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_approval_requests', to='sales.quotation')),
                ('resulting_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_source_quote', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('po_reference_number', models.CharField(help_text='Buyer Internal PO Number', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing in Warehouse'), ('SHIPPED', 'Dispatched / Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('requested_delivery_date', models.DateField()),
                ('shipping_carrier', models.CharField(blank=True, default='Standard Freight Delivery', max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b2b_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_orders', to='b2b_portal.b2baccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_self_orders', to='organizations.organization')),
                ('sales_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_portal_order', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b_portal.selfserviceorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_order_items', to='inventory.product')),
            ],
        ),
    ]
