# Generated by Django 5.0.6 on 2026-09-11 10:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sales', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSCouponPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FIXED', 'Fixed Currency Amount'), ('BUY_X_GET_Y', 'Buy X Get Y Free')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_discount_cap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 for no limit', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1000)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'POS Coupon / Promo',
                'verbose_name_plural': 'POS Coupons & Promotions',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.CreateModel(
            name='POSCustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze Tier'), ('SILVER', 'Silver Tier (5% extra points)'), ('GOLD', 'Gold Tier (10% extra points)'), ('PLATINUM', 'Platinum VIP (20% extra points)')], default='BRONZE', max_length=20)),
                ('lifetime_points_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_points_redeemed', models.PositiveIntegerField(default=0)),
                ('lifetime_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_loyalty', to='sales.customer')),
            ],
            options={
                'verbose_name': 'Customer Loyalty Card',
                'verbose_name_plural': 'Customer Loyalty Cards',
            },
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('order_type', models.CharField(choices=[('RETAIL', 'Walk-in Retail'), ('TAKEAWAY', 'Takeaway'), ('DINE_IN', 'Dine-In Restaurant'), ('DELIVERY', 'Express Delivery')], default='RETAIL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Cart'), ('COMPLETED', 'Completed & Paid'), ('VOIDED', 'Voided / Cancelled'), ('REFUNDED', 'Returned / Refunded')], default='COMPLETED', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('roundoff_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('change_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loyalty_points_earned', models.PositiveIntegerField(default=0)),
                ('loyalty_points_redeemed', models.PositiveIntegerField(default=0)),
                ('loyalty_discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.poscouponpromotion')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='sales.customer')),
            ],
            options={
                'verbose_name': 'POS Order Receipt',
                'verbose_name_plural': 'POS Order Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_order_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'POS Order Item',
                'verbose_name_plural': 'POS Order Items',
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed & Reconciled')], default='OPEN', max_length=20)),
                ('opening_notes', models.TextField(blank=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_pos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Session',
                'verbose_name_plural': 'POS Sessions',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash Counter'), ('CREDIT_CARD', 'Credit / Debit Card'), ('UPI_QR', 'UPI / QR Code Instant'), ('WALLET', 'Digital Wallet (ApplePay/GooglePay)'), ('LOYALTY', 'Loyalty Points Redemption'), ('STORE_CREDIT', 'Store Credit / Gift Card')], default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_network', models.CharField(blank=True, max_length=50)),
                ('auth_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed / Declined'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.posorder')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.possession')),
            ],
            options={
                'verbose_name': 'POS Payment Record',
                'verbose_name_plural': 'POS Payment Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.possession'),
        ),
        migrations.CreateModel(
            name='POSCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CASH_IN', 'Cash In / Add Float'), ('CASH_OUT', 'Cash Out / Expense / Payout'), ('SAFE_DROP', 'Safe Drop / Bank Transfer'), ('PETTY_EXPENSE', 'Petty Cash Local Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_pos_cash_txns', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='pos.possession')),
            ],
            options={
                'verbose_name': 'POS Cash Transaction',
                'verbose_name_plural': 'POS Cash Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('receipt_header', models.TextField(blank=True, default='Nexora Enterprise Retail\nThank you for shopping with us!')),
                ('receipt_footer', models.TextField(blank=True, default='Goods once sold can be exchanged within 7 days.\nVisit us at www.nexora-erp.io')),
                ('allow_offline_orders', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In-Service'), ('INACTIVE', 'Inactive / Closed'), ('MAINTENANCE', 'Under Maintenance'), ('LOCKED', 'Security Locked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='organizations.branch')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals_cash', to='accounting.account')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'POS Terminal',
                'verbose_name_plural': 'POS Terminals',
                'ordering': ['branch', 'terminal_code'],
            },
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.posterminal'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.posterminal'),
        ),
    ]
