# Generated by Django 5.0.6 on 2026-09-11 12:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cycle_type', models.CharField(choices=[('ANNUAL', 'Annual Performance & Compensation Review'), ('MID_YEAR', 'Mid-Year Milestone Check-in'), ('QUARTERLY', 'Quarterly OKR & Goal Review'), ('PROBATION', '90-Day Probationary Evaluation')], default='ANNUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('self_review_deadline', models.DateField()),
                ('manager_review_deadline', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Setup'), ('ACTIVE', 'Active in Review Process'), ('IN_CALIBRATION', 'Under Executive Calibration'), ('CLOSED', 'Cycle Finalized & Closed')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appraisal Cycle',
                'verbose_name_plural': 'Appraisal Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CORE_VALUE', 'Core Organizational Values & Ethics'), ('FUNCTIONAL_EXPERTISE', 'Functional / Technical Domain Excellence'), ('LEADERSHIP_MANAGEMENT', 'Leadership, Coaching & Strategic Vision'), ('INNOVATION_AGILITY', 'Innovation, Agility & Continuous Learning')], default='CORE_VALUE', max_length=30)),
                ('description', models.TextField(help_text='Behavioral indicators and measurement criteria')),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Competency Framework',
                'verbose_name_plural': 'Competency Frameworks',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContinuousFeedbackNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('PRAISE', 'Kudos / Public Peer Praise'), ('CONSTRUCTIVE', 'Constructive Coaching Observation'), ('CHECK_IN_NOTE', '1-on-1 Check-in Summary'), ('GOAL_MILESTONE', 'Goal / OKR Milestone Achieved')], default='PRAISE', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private_manager', models.BooleanField(default=False, help_text='Visible only to employee managers and HR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='hr.employee')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Continuous Feedback & 1-on-1 Note',
                'verbose_name_plural': 'Continuous Feedback & 1-on-1 Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=3)),
                ('self_summary', models.TextField(blank=True, help_text='Major accomplishments, OKR achievements, and learnings')),
                ('peer_average_rating', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=3)),
                ('manager_rating', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=3)),
                ('manager_summary', models.TextField(blank=True, help_text='Executive review, strengths, growth areas, promotion readiness')),
                ('calibrated_final_score', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=3)),
                ('overall_band', models.CharField(choices=[('OUTSTANDING', '5 - Top Tier / Outstanding (Top 10%)'), ('EXCEEDS', '4 - Exceeds Expectations'), ('MEETS', '3 - Consistently Meets Expectations'), ('NEEDS_IMPROVEMENT', '2 - Needs Improvement / Development Plan'), ('UNSATISFACTORY', '1 - Unsatisfactory Performance')], default='MEETS', max_length=25)),
                ('status', models.CharField(choices=[('PENDING_SELF', 'Pending Self Review'), ('PENDING_MANAGER', 'Pending Manager Review'), ('IN_CALIBRATION', 'Under Calibration Committee'), ('COMPLETED', 'Completed & Signed Off')], default='PENDING_SELF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='performance_appraisal.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_submissions', to='hr.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluated_appraisals', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Appraisal Submission',
                'verbose_name_plural': 'Appraisal Submissions',
                'ordering': ['-cycle', 'employee'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
