# Generated by Django 5.0.6 on 2026-09-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalRolePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position_code', models.CharField(max_length=50, unique=True)),
                ('risk_of_vacancy', models.CharField(choices=[('LOW', 'Low Vacancy Risk'), ('MEDIUM', 'Medium Vacancy Risk'), ('HIGH', 'High Vacancy Risk (Active Succession Priority)'), ('CRITICAL', 'Critical Immediate Vacancy Exposure')], default='MEDIUM', max_length=20)),
                ('impact_of_loss', models.CharField(choices=[('LOW', 'Low Operational Disruption'), ('MEDIUM', 'Moderate Operational Impact'), ('HIGH', 'High Strategic / Revenue Impact'), ('CRITICAL', 'Critical Mission-Essential Impact')], default='HIGH', max_length=20)),
                ('target_bench_strength', models.PositiveIntegerField(default=2, help_text='Number of ready successors required')),
                ('required_competencies', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_incumbent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incumbent_critical_roles', to='hr.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_roles', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Critical Role & Key Position',
                'verbose_name_plural': 'Critical Roles & Key Positions',
                'ordering': ['position_code'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_rating', models.CharField(choices=[('LOW', '1 - Low / Needs Development'), ('MEDIUM', '2 - Medium / Meets Expectations'), ('HIGH', '3 - High / Exceeds Expectations')], default='MEDIUM', max_length=10)),
                ('potential_rating', models.CharField(choices=[('LOW', '1 - Low / Lateral Role Fit'), ('MEDIUM', '2 - Medium / Growth Within Function'), ('HIGH', '3 - High / Cross-Functional Leadership Potential')], default='MEDIUM', max_length=10)),
                ('flight_risk', models.CharField(choices=[('LOW', 'Low Flight Risk'), ('MEDIUM', 'Medium Flight Risk'), ('HIGH', 'High Immediate Flight Risk')], default='LOW', max_length=10)),
                ('retention_risk_reason', models.CharField(blank=True, max_length=255)),
                ('nine_box_quadrant', models.CharField(choices=[('1_1', 'Risk / Underperformer (Low Perf, Low Pot)'), ('1_2', 'Inconsistent Performer (Low Perf, Med Pot)'), ('1_3', 'Rough Diamond (Low Perf, High Pot)'), ('2_1', 'Effective Professional (Med Perf, Low Pot)'), ('2_2', 'Core Talent / Key Player (Med Perf, Med Pot)'), ('2_3', 'High Potential / Rising Star (Med Perf, High Pot)'), ('3_1', 'Trusted Specialist / Solid Anchor (High Perf, Low Pot)'), ('3_2', 'High Performer (High Perf, Med Pot)'), ('3_3', 'Star / Top Tier Leadership (High Perf, High Pot)')], default='2_2', max_length=10)),
                ('key_strengths', models.TextField(blank=True)),
                ('career_aspirations', models.TextField(blank=True)),
                ('last_calibrated_at', models.DateField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Employee 9-Box Talent Profile',
                'verbose_name_plural': 'Employee 9-Box Talent Profiles',
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_level', models.CharField(choices=[('READY_NOW', 'Ready Now (< 3 Months)'), ('READY_1_YEAR', 'Ready in 1 Year'), ('READY_2_3_YEARS', 'Ready in 2-3 Years'), ('EMERGENCY_BACKUP', 'Emergency Contingency Cover')], default='READY_1_YEAR', max_length=25)),
                ('ranking_priority', models.PositiveIntegerField(default=1)),
                ('development_needs', models.TextField(blank=True, help_text='Executive mentorship, rotational assignments, technical certifications')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Candidate Nomination'), ('PROMOTED', 'Promoted into Role'), ('ARCHIVED', 'Archived / Reassigned')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('critical_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_candidates', to='succession_planning.criticalroleposition')),
                ('successor_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_nominations', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Succession Candidate Plan',
                'verbose_name_plural': 'Succession Candidate Plans',
                'ordering': ['critical_position', 'ranking_priority'],
                'unique_together': {('critical_position', 'successor_employee')},
            },
        ),
    ]
