# Generated by Django 5.0.6 on 2026-09-15 10:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='US', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_territories', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_code', models.CharField(max_length=50, unique=True)),
                ('skill_level', models.CharField(choices=[('APPRENTICE', 'Apprentice Technician (Level 1)'), ('JOURNEYMAN', 'Journeyman Specialist (Level 2)'), ('SENIOR_SPECIALIST', 'Senior Systems Specialist (Level 3)'), ('MASTER_ENGINEER', 'Master Field Systems Engineer (Level 4)')], default='JOURNEYMAN', max_length=30)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='field_service_fsm.serviceterritory')),
            ],
            options={
                'ordering': ['technician_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('CRITICAL_EMERGENCY', 'Critical Emergency (2-Hour SLA)'), ('HIGH', 'High Priority (4-Hour SLA)'), ('MEDIUM', 'Medium (Next Business Day)'), ('LOW', 'Low Priority (Scheduled Maintenance)')], default='HIGH', max_length=30)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned / Pending Dispatch'), ('DISPATCHED', 'Dispatched to Technician'), ('EN_ROUTE', 'En Route to Site'), ('ON_SITE', 'Technician On Site'), ('WORK_IN_PROGRESS', 'Work in Progress'), ('COMPLETED', 'Completed & Signed Off'), ('CANCELLED', 'Cancelled')], default='UNASSIGNED', max_length=30)),
                ('sla_deadline', models.DateTimeField()),
                ('scheduled_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('issue_summary', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('service_address', models.TextField(default='Customer Industrial Facility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='field_service_fsm.servicetechnician')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsm_work_orders', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='organizations.organization')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='field_service_fsm.serviceterritory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('inventory_deducted', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsm_consumptions', to='inventory.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_parts', to='field_service_fsm.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(max_length=100)),
                ('signatory_title', models.CharField(blank=True, max_length=100)),
                ('satisfaction_rating', models.PositiveIntegerField(default=5)),
                ('feedback_notes', models.TextField(blank=True)),
                ('digital_signature_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signoff', to='field_service_fsm.workorder')),
            ],
        ),
    ]
