# Generated by Django 5.0.6 on 2026-09-11 12:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift_code', models.CharField(max_length=30, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration_minutes', models.PositiveIntegerField(default=45)),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('hourly_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shift Template',
                'verbose_name_plural': 'Shift Templates',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BiometricPunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('punch_type', models.CharField(choices=[('CLOCK_IN', 'Clock In (Shift Start)'), ('CLOCK_OUT', 'Clock Out (Shift End)'), ('BREAK_START', 'Meal / Rest Break Start'), ('BREAK_END', 'Meal / Rest Break Return')], default='CLOCK_IN', max_length=20)),
                ('device_terminal_id', models.CharField(default='TERM-MAIN-01', max_length=50)),
                ('verification_method', models.CharField(choices=[('FACIAL_RECOGNITION', 'AI Facial Recognition Biometric Terminal'), ('FINGERPRINT', 'Optical Fingerprint Scanner'), ('RFID_BADGE', 'NFC / RFID Security Badge'), ('MOBILE_GPS', 'Mobile App Geo-Fenced Punch'), ('MANUAL_HR', 'HR Manual Override Approval')], default='FACIAL_RECOGNITION', max_length=30)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_punches', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Biometric Punch Log',
                'verbose_name_plural': 'Biometric Punch Logs',
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed by Employee'), ('SWAPPED', 'Shift Swapped'), ('CANCELLED', 'Cancelled / Leave Off')], default='SCHEDULED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignments', to='hr.employee')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_rosters', to='shifts_rostering.shifttemplate')),
            ],
            options={
                'verbose_name': 'Shift Roster Assignment',
                'verbose_name_plural': 'Shift Roster Assignments',
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummaryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('regular_hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overtime_1_5x_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overtime_2_0x_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PRESENT', 'On Time / Normal Shift'), ('LATE', 'Tardy / Late Arrival'), ('EARLY_DEPARTURE', 'Early Departure'), ('ABSENT', 'Unexcused Absence'), ('ON_LEAVE', 'Approved Paid Leave')], default='PRESENT', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_summaries', to='hr.employee')),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts_rostering.shifttemplate')),
            ],
            options={
                'verbose_name': 'Daily Timesheet & Overtime Summary',
                'verbose_name_plural': 'Daily Timesheet & Overtime Summaries',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
