# Generated by Django 5.0.6 on 2026-09-11 12:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxJurisdictionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('statutory_tax_name', models.CharField(help_text='e.g. US Federal Income Tax & FICA', max_length=150)),
                ('income_tax_effective_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('social_security_rate', models.DecimalField(decimal_places=2, default=Decimal('6.20'), max_digits=5)),
                ('healthcare_insurance_rate', models.DecimalField(decimal_places=2, default=Decimal('1.45'), max_digits=5)),
                ('pension_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('employer_contribution_rate', models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tax Jurisdiction Statutory Rule',
                'verbose_name_plural': 'Tax Jurisdiction Statutory Rules',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='PayRunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('pay_date', models.DateField()),
                ('total_gross_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_statutory_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_net_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_payslips_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Batch Run'), ('CALCULATED', 'Gross-to-Net Calculated'), ('APPROVED', 'Approved by CFO / Payroll Director'), ('POSTED_GL', 'Posted to General Ledger')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pay Run Batch',
                'verbose_name_plural': 'Pay Run Batches',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('base_monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localized_salary_structure', to='hr.employee')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='localized_payroll.taxjurisdictionrule')),
            ],
            options={
                'verbose_name': 'Employee Salary Structure',
                'verbose_name_plural': 'Employee Salary Structures',
                'ordering': ['employee'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('base_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statutory_income_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('social_insurance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pension_employee_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Calculated'), ('FINALIZED', 'Finalized & Locked'), ('PAID', 'Disbursed & Paid')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_payslips', to='hr.employee')),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='localized_payroll.payrunbatch')),
            ],
            options={
                'verbose_name': 'Employee Itemized Payslip',
                'verbose_name_plural': 'Employee Itemized Payslips',
                'ordering': ['-pay_run', 'employee'],
                'unique_together': {('pay_run', 'employee')},
            },
        ),
    ]
