# Generated by Django 5.0.6 on 2026-09-11 10:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceIRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irn_hash', models.CharField(help_text='64-Character SHA-256 Invoice Reference Number', max_length=64, unique=True)),
                ('ack_number', models.CharField(max_length=50, unique=True)),
                ('ack_date', models.DateTimeField()),
                ('invoice_number', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('seller_gstin', models.CharField(max_length=20)),
                ('buyer_gstin', models.CharField(blank=True, max_length=20)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('qr_code_payload', models.TextField(help_text='Signed QR String Data from Government IRP')),
                ('signed_invoice_jwt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Valid IRN'), ('CANCELLED', 'Cancelled with IRP')], default='ACTIVE', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'e-Invoice IRN',
                'verbose_name_plural': 'e-Invoice IRNs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EUVATRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_state_code', models.CharField(help_text='e.g. DE, FR, IT, ES, NL', max_length=5, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('standard_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('reduced_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('super_reduced_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('oss_scheme_enabled', models.BooleanField(default=True, help_text='One-Stop-Shop EU Cross-Border B2C')),
                ('reverse_charge_b2b', models.BooleanField(default=True)),
                ('vies_validation_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EU VAT Rule (OSS/VIES)',
                'verbose_name_plural': 'EU VAT Rules (OSS/VIES)',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='HSNSACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('code_type', models.CharField(choices=[('HSN', 'HSN (Harmonized System of Nomenclature - Goods)'), ('SAC', 'SAC (Services Accounting Code - Services)')], default='HSN', max_length=10)),
                ('standard_gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Total GST % (e.g. 5, 12, 18, 28)', max_digits=5)),
                ('is_exempt', models.BooleanField(default=False)),
                ('is_nil_rated', models.BooleanField(default=False)),
                ('rcm_applicable', models.BooleanField(default=False, help_text='Reverse Charge Mechanism Applicable')),
            ],
            options={
                'verbose_name': 'HSN / SAC Master',
                'verbose_name_plural': 'HSN / SAC Masters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IN', 'India (GST / TCS / TDS)'), ('US', 'United States (State & Local Sales Tax)'), ('EU', 'European Union (VAT / OSS / VIES)'), ('UK', 'United Kingdom (HMRC Making Tax Digital)'), ('AE', 'United Arab Emirates (FTA VAT 5%)'), ('SG', 'Singapore (IRAS GST 9%)'), ('AU', 'Australia (ATO GST 10%)'), ('CA', 'Canada (GST / HST / PST / QST)'), ('GLOBAL', 'Global / Generic Jurisdiction')], default='IN', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('tax_authority_name', models.CharField(default='Central Tax Authority', max_length=200)),
                ('filing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly Filing'), ('QUARTERLY', 'Quarterly Filing'), ('ANNUAL', 'Annual Filing')], default='MONTHLY', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('e_invoicing_mandatory', models.BooleanField(default=False)),
                ('e_way_bill_mandatory', models.BooleanField(default=False)),
                ('e_way_bill_threshold', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Jurisdiction',
                'verbose_name_plural': 'Tax Jurisdictions',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='USStateNexusRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(help_text='e.g. CA, NY, TX, FL, WA', max_length=5, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_sales_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('avg_local_sales_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('economic_nexus_revenue_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='e.g. $100,000 threshold', max_digits=12)),
                ('economic_nexus_txn_threshold', models.PositiveIntegerField(default=200, help_text='e.g. 200 transactions')),
                ('has_physical_nexus', models.BooleanField(default=False)),
                ('has_economic_nexus', models.BooleanField(default=False)),
                ('is_origin_based_tax', models.BooleanField(default=False, help_text='True for origin-based states (TX, OH, etc.), False for destination-based')),
            ],
            options={
                'verbose_name': 'US State Tax & Economic Nexus',
                'verbose_name_plural': 'US State Taxes & Economic Nexus',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='EWayBillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewb_number', models.CharField(max_length=50, unique=True)),
                ('document_number', models.CharField(help_text='Invoice or Delivery Challan Number', max_length=64)),
                ('document_type', models.CharField(default='TAX_INVOICE', max_length=20)),
                ('transport_mode', models.CharField(choices=[('ROAD', 'Road Freight'), ('RAIL', 'Railways'), ('AIR', 'Air Cargo'), ('SHIP', 'Sea / Ocean Vessel')], default='ROAD', max_length=10)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('transporter_id', models.CharField(blank=True, help_text='GSTIN of Transporter', max_length=50)),
                ('transporter_name', models.CharField(blank=True, max_length=150)),
                ('distance_km', models.PositiveIntegerField(default=100)),
                ('from_pincode', models.CharField(max_length=20)),
                ('to_pincode', models.CharField(max_length=20)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated & Active'), ('IN_TRANSIT', 'Goods In-Transit'), ('DELIVERED', 'Delivered & Closed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Validity Expired')], default='GENERATED', max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-Way Bill Record',
                'verbose_name_plural': 'e-Way Bill Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFilingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('GSTR_1', 'GSTR-1 Outward Supplies (India)'), ('GSTR_3B', 'GSTR-3B Summary Return & ITC (India)'), ('GSTR_9', 'GSTR-9 Annual GST Audit Return (India)'), ('EU_OSS_VAT', 'EU One-Stop-Shop VAT Return'), ('UK_MTD_VAT', 'UK HMRC MTD VAT Return'), ('US_SALES_TAX', 'US State Sales & Use Tax Return'), ('FORM_1099_MISC', 'US IRS Form 1099-MISC')], max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_taxable_turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_itc_claimed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Input Tax Credit', max_digits=14)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Summary'), ('VALIDATED', 'Validated by Engine'), ('FILED', 'Filed with Government Portal'), ('ACCEPTED', 'Accepted by Tax Department'), ('REJECTED', 'Rejected / Requires Amendment')], default='DRAFT', max_length=20)),
                ('government_arn_reference', models.CharField(blank=True, help_text='Acknowledgement Reference Number', max_length=100)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_metrics_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to='taxation.taxjurisdiction')),
            ],
            options={
                'verbose_name': 'Tax Filing & Statutory Return',
                'verbose_name_plural': 'Tax Filings & Statutory Returns',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Central GST %', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='State / UT GST %', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Integrated GST %', max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Compensation Cess %', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_rates', to='taxation.taxjurisdiction')),
            ],
            options={
                'verbose_name': 'GST Tax Slab',
                'verbose_name_plural': 'GST Tax Slabs',
                'ordering': ['-effective_from'],
            },
        ),
    ]
