# Generated by Django 5.0.6 on 2026-09-11 10:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('id_passport_number', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='United States', max_length=100)),
                ('vip_tier', models.CharField(choices=[('STANDARD', 'Standard Guest'), ('SILVER', 'Silver Elite'), ('GOLD', 'Gold Preferred'), ('PLATINUM', 'Platinum Executive VIP'), ('CELEBRITY', 'VVIP Ambassador')], default='STANDARD', max_length=20)),
                ('special_preferences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30, unique=True)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / Vacant Clean'), ('OCCUPIED', 'Occupied / In-House'), ('RESERVED', 'Reserved for Arrival'), ('CLEANING', 'Housekeeping / Dirty'), ('MAINTENANCE', 'Out of Order / Maintenance')], default='AVAILABLE', max_length=20)),
                ('keycard_lock_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('base_occupancy', models.PositiveIntegerField(default=2)),
                ('max_occupancy', models.PositiveIntegerField(default=4)),
                ('base_nightly_rate', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestFolioInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=50, unique=True)),
                ('total_room_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_incidentals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open Folio (In-House)'), ('SETTLED', 'Settled & Paid In Full'), ('VOID', 'Voided / Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='hospitality_pms.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FolioChargeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('ROOM_NIGHT', 'Room Accommodation Charge'), ('RESTAURANT', 'In-Room Dining / Restaurant'), ('MINIBAR', 'Minibar Refreshments'), ('SPA_WELLNESS', 'Spa, Massage & Wellness'), ('LAUNDRY', 'Valet Laundry Service'), ('TRANSPORT', 'Airport Limousine Transfer'), ('RESORT_FEE', 'Daily Resort / Amenity Fee')], default='ROOM_NIGHT', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_lines', to='hospitality_pms.guestfolioinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CHECKOUT_DEEP_CLEAN', 'Full Departure Deep Cleaning'), ('STAY_OVER_CLEAN', 'Stay-Over Daily Refresh'), ('TURNDOWN', 'Evening Turndown Service'), ('LINEN_CHANGE', 'Complete Linen & Towel Swap'), ('SANITIZE', 'Full Sanitization Inspection')], default='CHECKOUT_DEEP_CLEAN', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('IN_PROGRESS', 'Cleaning In Progress'), ('INSPECTED_CLEAN', 'Inspected Clean / Ready for Guest'), ('NEEDS_REWORK', 'Failed Inspection / Needs Rework')], default='PENDING', max_length=20)),
                ('assigned_housekeeper', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hospitality_pms.hotelroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=50, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_room_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_source', models.CharField(choices=[('DIRECT_DESK', 'Front Desk Walk-in / Phone'), ('WEBSITE', 'Direct Website Booking Engine'), ('BOOKING_COM', 'Booking.com OTA Channel'), ('EXPEDIA', 'Expedia Partner Network'), ('AGODA', 'Agoda Global'), ('CORPORATE', 'Corporate Travel Contract')], default='DIRECT_DESK', max_length=30)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed Booking'), ('CHECKED_IN', 'Checked In (In-House)'), ('CHECKED_OUT', 'Checked Out (Departed)'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=20)),
                ('actual_check_in_time', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out_time', models.DateTimeField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hospitality_pms.guestprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hospitality_pms.hotelroom')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hospitality_pms.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='guestfolioinvoice',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='hospitality_pms.roomreservation'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hospitality_pms.roomtype'),
        ),
    ]
