# Generated by Django 5.0.6 on 2026-09-11 11:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciableAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(default='Machinery & Robotics', max_length=100)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-Line Depreciation (IAS 16 / GAAP)'), ('DOUBLE_DECLINING', '200% Double-Declining Balance (Accelerated)'), ('MACRS_5YR', 'MACRS 5-Year Property Table (Tax Accelerated)'), ('MACRS_7YR', 'MACRS 7-Year Property Table (Industrial Machinery)'), ('SUM_OF_YEARS', 'Sum-of-the-Years Digits (SYD)')], default='STRAIGHT_LINE', max_length=30)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active in Service'), ('FULLY_DEPRECIATED', 'Fully Depreciated (Zero Net Book Value)'), ('DISPOSED', 'Disposed / Sold Off'), ('IMPAIRED', 'Impaired per IAS 36')], default='ACTIVE', max_length=25)),
                ('location_facility', models.CharField(default='Main Advanced Manufacturing Plant', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accumulated_depr_gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('asset_gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('depreciation_expense_gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Depreciable Fixed Asset',
                'verbose_name_plural': 'Depreciable Fixed Assets',
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetImpairmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('carrying_amount_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recoverable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impairment_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(help_text='Technological obsolescence, damage, or adverse market shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impairments', to='fixed_assets_depr.depreciableasset')),
            ],
            options={
                'verbose_name': 'Asset Impairment Test (IAS 36)',
                'verbose_name_plural': 'Asset Impairment Tests (IAS 36)',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('sale_proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gain_loss_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buyer_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='fixed_assets_depr.depreciableasset')),
            ],
            options={
                'verbose_name': 'Asset Disposal & Derecognition',
                'verbose_name_plural': 'Asset Disposals & Derecognitions',
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('opening_book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedule', to='fixed_assets_depr.depreciableasset')),
            ],
            options={
                'verbose_name': 'Asset Depreciation Period',
                'verbose_name_plural': 'Asset Depreciation Periods',
                'ordering': ['period_date'],
                'unique_together': {('asset', 'period_date')},
            },
        ),
    ]
